# -*- coding: utf-8 -*-
"""Subscribe.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rhhjoUUlIC-07QiXNpzuPKqG-tHkgJVs
"""

import rospy
from std_msgs.msg import String

def callback(data):
    rospy.loginfo("Received message: %s", data.data)

rospy.init_node('navigation_subscriber')
rospy.Subscriber('/robot_status', String, callback)

rospy.spin()
